version: "3.8"

services:
  database:
    image: postgres:latest
    container_name: postgres_database
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DATABASE=postgres
    ports:
      - "5432:5432"
#  backend:
#    container_name: software-testing-crud
#    build:
#      context: .
#      dockerfile: Dockerfile
#    depends_on:
#      - database
#    ports:
#      - "8080:8080"
