spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: false